name: Trigger auto deployment for openlist

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/openlist-AutoDeployTrigger-4a40f03d-a951-48e3-a803-2967321f9add.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OPENLIST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENLIST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPENLIST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.OPENLIST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OPENLIST_REGISTRY_PASSWORD }}
          containerAppName: openlist
          resourceGroup: NetworkWatcherRG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


